name: CI

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/main.yml"
      - "app/**/*.ts"
      - "app/**/*.tsx"
      - "public/*"
      - "styles/*"
      - "worker/*"
      - "tests/**"
      - "package.json"
      - "package-lock.json"
      - "remix.config.js"
      - "tsconfig.json"
      - "wrangler.toml"
      - "remix.env.d.ts"
      - "tailwind.config.js"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm test
      - run: npx playwright install --with-deps chromium
      - run: npm run test:e2e
      - run: npm run build
